# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a8525e27c14e403060228a134905f6b087cdf32c77e7d09c9b6d9cd48ddb1d7963ce2b321e97bc76c19ee5d7f5e7ce45f82fc17395b269b96fba7106164dd5c

test:
  secret_key_base: 1eb47daa93f30f36795680cfded8d95fe2b980f03ebc0f85d7661b4582f05a437e3e8cb82c0cae74c2fd8137022c0428417bf4f50eda3b34f35683d8141dc7c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
